### PR TITLE
 Fix app crash when BLE is disabled on application start

### PR DESCRIPTION
**Pull request by GArik**
* Move BLE scanner setup after checking whether BLE is activated;
* Require ACCESS_FINE_LOCATION for BLE. According to Android docs having coarse location access is not enough for Android 10: https://developer.android.com/guide/topics/connectivity/bluetooth-le.html#permissions

### CODE REVIEW

**Comment by perssonmagnus** [comment]
Hi,

Thanks for your input. This repository is a mirror of an internal closed repository and as such we do not take in pull requests directly (and do not watch it very closely, hence the late answer, sorry about that).

We are, however looking into the input, and the application crash you have reported is corrected and the issue with fine location is looked into. It has worked without on the Android 10 phones tested so far but the documentation indeed suggests that it is needed.

Best Regards,
Magnus

**Comment by GArik** [comment]
So, will the crash be fixed in the next release? Should I close this PR?

**Comment by perssonmagnus** [comment]
Hi Igor,

Yes, the crash will be fixed and we can close this PR.
Again, thanks a lot for the input, and we are happy to receive any further input in the same way.

Best Regards,
Magnus

**Comment by GArik** [comment]
Ok. Thank you for your application. Take care.

**Pull request closed without merging**
